site_name: COMP423 Course Notes
theme:
  name: material

markdown_extensions:
  - codehilite        # Syntax highlighting for code blocks
  - admonition        # Callouts for notes, warnings, etc.
  - toc               # Table of contents